# Generated by Django 4.0.2 on 2022-02-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_myworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
